### PR TITLE
Update boltons to 16.5.0

### PR DESCRIPTION
**Pull request by nicoddemus**
Also update the template to use the package from PyPI

### CODE REVIEW

**Comment by nicoddemus** [comment]
Hmm just noticed that the `boltons` package on PyPI doesn't contain the test files. Reverting to use the GitHub arquive is not really possible right now because `16.5.0` is not available in [releases](https://github.com/mahmoud/boltons/releases) (mahmoud/boltons#100).

Should we:

1. Skip tests while building the package? That's what I usually do: perform just some light testing to ensure the package is correct (like importing the package) and trust that the package maintainer has done the proper testing himself;
2. Wait until mahmoud/boltons#100 is fixed and revert the recipe to use the GitHub release?

**Comment by ocefpaf** [comment]
I find it troubling that people do not tag the releases on GitHub but that happens. I would not wait for it though.

Some people do not package the tests b/c they rely on the CI at the source and there is not much to test once packaged besides a "import <pkg>". So I would go for option `1`.

**Comment by nicoddemus** [comment]
FWIW mahmoud/boltons#100 has been fixed already.

But I still think `1` is the best option. @kalefranz what do you think?

**Comment by nicoddemus** [comment]
I replaced testing by imports as we discussed, and added myself as maintainer.

**Comment by nicoddemus** [comment]
Also rebased on #1

**Comment by kalefranz** [comment]
Sorry I missed being tagged here 8 days ago.

I prefer to run the full unit tests, and I think it's unfortunate that a lot of recipes have been written that don't.  The unit tests are a much better way to guarantee that a package's dependencies support the current version of a package.  When a dependency is updated, ideally the CI system would be able to go back through a re-test (though not re-build!) all of the packages that depend on it.

We don't have that CI system now, but it will be built somewhere, someday.  It would be nice if the recipes were already in a state to effectively use it.

Also, @ocefpaf, we read tests from the *source directory*, not from the built package.  However, we test against the built package that's installed in the test environment.

**Comment by kalefranz** [comment]
Plus, actually running those tests found several issues that were reported upstream and promptly fixed.  See: https://github.com/conda-forge/staged-recipes/pull/560#issuecomment-218174935

**Comment by nicoddemus** [comment]
@kalefranz no worries, I understand your points.

Reverted to using a package and running the actual tests. Let me know if you would like to change something else.

**Comment by kalefranz** [comment]
LGTM. If tests pass I'll hit the merge button

**Comment by nicoddemus** [comment]
The AppVeyor and Travis failed with strange errors, so I'm running them again to see if it was a fluke.

**Comment by jakirkham** [comment]
Needs to be [re-rendered]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with `conda-smithy` version `1.4.6`.

**Comment by nicoddemus** [comment]
Re-rendered. 😁 

Thanks for the advice @jakirkham

**Comment by jakirkham** [comment]
Of course. 😄

**Comment by nicoddemus** [comment]
It seems ready to be merged. 😁

**Comment by nicoddemus** [comment]
Re-rendered with conda-smithy `1.6.1`.

There's been already a `16.5.1` release, but I think we should merge this first.

**Comment by nicoddemus** [comment]
@kalefranz, gentle ping. 👍

**Comment by jakirkham** [comment]
Hoping I'm not overstepping @kalefranz, but am going to merge this so some of the backlog can be cleared at this feedstock.

**Pull request merged**
