### PR TITLE
maintence

### PR DESCRIPTION
**Pull request by tacaswell**
To reduce chance of collision with other packages and to help humans
who look at the source cache directory.

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks @tacaswell, but this has been superseded by #5, #6 and #7. 👍

**Comment by tacaswell** [comment]
I think the change in https://github.com/conda-forge/boltons-feedstock/pull/4/files#diff-e178b687b10a71a3348107ae3154e44cR8 to add the package name to the downloaded file is worth including (and looks like it got lost).

**Comment by tacaswell** [comment]
sorry for dredging back up an old issue, I finally got to this in my mentions ;)

**Comment by nicoddemus** [comment]
I agree, sorry about that. Feel free to submit a new PR, otherwise I will try to remember to add it back for the next release! 👍

**Pull request closed without merging**
